name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, aarch64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          pyinstaller --onefile niimprint/__main__.py --name niimprint-${{ matrix.os }}-${{ matrix.arch }}.exe
        else
          pyinstaller --onefile niimprint/__main__.py --name niimprint-${{ matrix.os }}-${{ matrix.arch }}
        fi

    - name: Check if file exists
      run: |
        ls -la dist/
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          mv dist/niimprint-${{ matrix.os }}-${{ matrix.arch }}.exe dist/niimprint-windows-latest-${{ matrix.arch }}.exe
        else
          mv dist/niimprint-${{ matrix.os }}-${{ matrix.arch }} dist/niimprint-${{ matrix.os }}-${{ matrix.arch }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: niimprint-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts for Ubuntu x64
      uses: actions/download-artifact@v3
      with:
        name: niimprint-ubuntu-latest-x64
        path: ./release/ubuntu-latest-x64

    - name: Download Artifacts for Ubuntu aarch64
      uses: actions/download-artifact@v3
      with:
        name: niimprint-ubuntu-latest-aarch64
        path: ./release/ubuntu-latest-aarch64

    - name: Download Artifacts for Windows x64
      uses: actions/download-artifact@v3
      with:
        name: niimprint-windows-latest-x64
        path: ./release/windows-latest-x64

    - name: Download Artifacts for Windows aarch64
      uses: actions/download-artifact@v3
      with:
        name: niimprint-windows-latest-aarch64
        path: ./release/
